[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    adafruit/DHT sensor library@^1.4.4
    knolleary/PubSubClient@^2.8
    ESP32Servo@^1.0.3
    ArduinoJson@^6.21.3